### ISSUE TITLE
Found some more for your list

### ISSUE THREAD

**Issue by KingDrewcifer** [directorcia/Office365#1]
MCOPSTN1 = Domestic Calling Plan
MCOPSTNC = Communications Credits
MCOPSTN2 = Domestic and International Calling Plan
MCOMEETACPEA	= Audio Conferencing Pay-Per-Minute
POWERAPPS_VIRAL = Microsoft PowerApps Plan 2 Trial

**Comment by directorcia** [comment]
added. Thanks
