### ISSUE TITLE
Specify individual permissions to remove

### ISSUE THREAD

**Issue by paddymccallan** [directorcia/Office365#12]
this code is great for removing all permissions, but since it gives you a list of the permissions it would be nice to specify an individual one as opposed to all them. Be very handy. Not actually an issue but can change to feature request! Thanks

**Comment by komodo2** [comment]
Agreed. Love the script but I actually only need to remove one user consent not all.

**Comment by directorcia** [comment]
Can you tell me the file you are talking about in the repo and I'll take a look.

**Comment by komodo2** [comment]
https://github.com/directorcia/Office365/blob/master/graph-adappperm-del.ps1

You could just do another Out-GridView so that individual consent permissions could be selected and removed. Awesome if you could do that!

**Comment by directorcia** [comment]
I have updated the source to allow selection BUT the permissions as group by API, this if you have 2 Graph permissions you have to delete them both together. There is no easy way of removing just one consent from a single API without a major rework of the whole script I'm sorry to say.

**Comment by komodo2** [comment]
Thanks for giving it a try! In my case they were all Graph permissions.

**Comment by directorcia** [comment]
Getting to individual Graph permissions is a major job and from memory I did it my proprietary code available at www.ciaopspatron.com. This script is just general.
