### ISSUE TITLE
Skus need updating

### ISSUE THREAD

**Issue by martincaddick** [directorcia/Office365#14]
EMSPREMIUM = ENTERPRISE MOBILITY + SECURITY E5
May be others, I haven't checked.
Very nice work btw.

**Comment by directorcia** [comment]
Upadted.
Appreciate the feedback

**Comment by martincaddick** [comment]
Further updates, no more ;-)

"CRMPLAN2" = "MICROSOFT DYNAMICS CRM ONLINE BASIC"
"DYN365_TEAM_MEMBERS" = "DYNAMICS 365 TEAM MEMBERS"
"WINDOWS_STORE" = "WINDOWS STORE FOR BUSINESS"
"CDSAICAPACITY" = "AI Builder Capacity add-on"
"CRM_ONLINE_PORTAL" = "Dynamics 365 Enterprise Edition - Additional Portal (Qualified Offer)"
"PBI_PREMIUM_P1_ADDON" = "Power BI Premium P1"
"MDATP_Server" = "Microsoft Defender for Endpoint Server"
"DYN365_ENTERPRISE_CUSTOMER_SERVICE" = "DYNAMICS 365 FOR CUSTOMER SERVICE ENTERPRISE EDITION"
"CRMTESTINSTANCE" = "Dynamics 365 - Additional Non-Production Instance (Qualified Offer)"
"WIN_DEF_ATP" = "MICROSOFT DEFENDER FOR ENDPOINT"
"IDENTITY_THREAT_PROTECTION_FOR_EMS_E5" = "Microsoft 365 E5 Security for EMS E5"
"SPE_E5" = "Microsoft 365 E5"
"POWERAPPS_PER_USER" = "Power Apps per user plan"
"CRMINSTANCE" = "Dynamics 365 - Additional Production Instance (Qualified Offer)"
"POWERAUTOMATE_ATTENDED_RPA" = "Power Automate per user with attended RPA plan"

**Comment by directorcia** [comment]
Updated. Thanks.
