### ISSUE TITLE
Permission Errors when using Defender365 call

### ISSUE THREAD

**Issue by SearchForTheCode** [directorcia/Office365#22]
Did you have any problems with the vulnerability API on defender? 
I set the same rights, but always ( only with this call, machine info works) run in an 403 error!

Following the blog, it seems correct. 
https://blog.ciaops.com/2021/06/15/using-the-defender-for-endpoint-api-and-powershell/

![image](https://github.com/directorcia/Office365/assets/9859622/fb79370c-e84b-498d-9e72-9cae009c84a3)

The rights on my token are definitly correct and granted in UI:
![image](https://github.com/directorcia/Office365/assets/9859622/52e7ff3e-5b5f-4713-aec9-fe5ae80ec303)

**Comment by directorcia** [comment]
Make the call to the GET /api/vulnerabilities/machinesVulnerabilities - https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-all-vulnerabilities-by-machines?view=o365-worldwide which works for me

**Comment by SearchForTheCode** [comment]
Interesting, i tried that too, same error! But it seems to be an M365 endpoint specific error. because in my own M365 environment i dont receive this error and it works too.

Thank you :)
