### ISSUE TITLE
win10-asr-get.ps1 - Broken for standard users with Defender version 4.18.23070.1004-0

### ISSUE THREAD

**Issue by PaulHarfield** [directorcia/Office365#24]
It looks like this is now broken for standard users as of 14/08/2023. The rule IDs (AttackSurfaceReductionRules_Ids) and exclusions are no longer visible in get-mppreference . Might need a check for admin rights and report error as it currently just shows 0 rules applied

**Comment by directorcia** [comment]
Fixed
