### ISSUE TITLE
Office365 /mggraph-sscore-get.ps1

### ISSUE THREAD

**Issue by Elilitha** [directorcia/Office365#26]
Love this code. Just a suggestion

Line 43: $scopes = "SecurityEvents.ReadWrite.All"
change to
$scopes = "SecurityEvents.Read.All"

Following Microsoft suggestion of Least privileged permissions
https://learn.microsoft.com/en-us/graph/api/securescore-get?view=graph-rest-1.0&tabs=powershell

**Comment by directorcia** [comment]
Great suggestion. Updated
