### ISSUE TITLE
Placeholder for API key

### ISSUE THREAD

**Issue by cornholioso** [directorcia/Office365#3]
Good to also insert the code to allow the API key to be used - may be best to pull the code directly from the updated HIBP script https://gcits.com/knowledge-base/check-office-365-accounts-against-have-i-been-pwned-breaches/

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Connect-MsolService
$HIBPAPIKey = "YOURHIBPAPIKEY"
$headers = @{
    "hibp-api-key"  = $HIBPAPIKey
}
$baseUri = "https://haveibeenpwned.com/api/v3"
$users = Get-msoluser -All

**Comment by biobenchsolutions** [comment]
Can you explain more better and does office 365 page uses api key

**Comment by directorcia** [comment]
If you want to connect to HAveIbeenPwned you need to pay a subscription  and this gets you an API key you can use.
