### ISSUE TITLE
Can you help me on this line?

### ISSUE THREAD

**Issue by tczanardo** [directorcia/Office365#4]
https://github.com/directorcia/Office365/blob/74f4354ea0f5ffae530ca7f9f7c68778edcb02d8/o365-spam-policy.ps1#L20

Thanks for the script, I have based on yours to create my own.

You recommended creating the $domains = "d1.com", "d2.com"
I was struggling to create an automatic way to fill this $domains.
I tried this but didn't work as you recommended:

$Domains = (Get-AcceptedDomain).DomainName -join ", "
or
$Domains = Read-Host "Enter all domains separated by comma e.g. d1.com,d2.com,d3.com"

Can you help me pls?

**Comment by directorcia** [comment]
write-host -foregroundcolor $processmessagecolor "Start - Get all domains in tenant "
$domains = Get-Msoldomain
$recipientdomain = Foreach ($domain in $domains){
    $domain.name
}
write-host -foregroundcolor $processmessagecolor "Finish - Get all domains in tenant "
