### ISSUE TITLE
Color Variable Error during script exec

### ISSUE THREAD

**Issue by cornholioso** [directorcia/Office365#9]
Issue: Three color variables defined at start of script but $warningmessagecolor is later referenced but not defined

$systemmessagecolor = "cyan"
$processmessagecolor = "green"
$errormessagecolor= "red"

137: $displaycolor = $errormessagecolor, $processmessagecolor, $warningmessagecolor'

If triggered, errors would appear as below:

Write-Host : Cannot bind parameter 'ForegroundColor' to the target. Exception setting "ForegroundColor": "Cannot convert null to type
"System.ConsoleColor" due to enumeration values that are not valid. Specify one of the following enumeration values and try again. The possible
enumeration values are "Black,DarkBlue,DarkGreen,DarkCyan,DarkRed,DarkMagenta,DarkYellow,Gray,DarkGray,Blue,Green,Cyan,Red,Magenta,Yellow,White"."
At C:\GitHub\Office365\win10-asr-get.ps1:137 char:44
+ ...        2 {write-host -foregroundcolor $displaycolor[$enabled] $asrrul ...
+                                           ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Write-Host], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Commands.WriteHostCommand

Write-Host : Cannot bind parameter 'ForegroundColor' to the target. Exception setting "ForegroundColor": "Cannot convert null to type
"System.ConsoleColor" due to enumeration values that are not valid. Specify one of the following enumeration values and try again. The possible
enumeration values are "Black,DarkBlue,DarkGreen,DarkCyan,DarkRed,DarkMagenta,DarkYellow,Gray,DarkGray,Blue,Green,Cyan,Red,Magenta,Yellow,White"."
At C:\GitHub\Office365\win10-asr-get.ps1:137 char:44
+ ...        2 {write-host -foregroundcolor $displaycolor[$enabled] $asrrul ...
+                                           ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Write-Host], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Commands.WriteHostCommand

Write-Host : Cannot bind parameter 'ForegroundColor' to the target. Exception setting "ForegroundColor": "Cannot convert null to type
"System.ConsoleColor" due to enumeration values that are not valid. Specify one of the following enumeration values and try again. The possible
enumeration values are "Black,DarkBlue,DarkGreen,DarkCyan,DarkRed,DarkMagenta,DarkYellow,Gray,DarkGray,Blue,Green,Cyan,Red,Magenta,Yellow,White"."
At C:\GitHub\Office365\win10-asr-get.ps1:137 char:44
+ ...        2 {write-host -foregroundcolor $displaycolor[$enabled] $asrrul ...
+                                           ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Write-Host], ParameterBindingException
    + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Commands.WriteHostCommand

**Comment by directorcia** [comment]
Fixed
